language: go

go:
  - 1.9

services:
  - postgres


before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/gorilla/mux

script:
  - go test -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci